### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by staceycy** [StanfordVL/STR-PIP#1]
Hi, 

Thank you for your awesome work and I am quite interested in it. 
Could you please kindly tell me when do you plan to release the code? 

Thank you very much. 

Best,
Stacey

**Comment by MrYu001** [comment]
the same as me, thank you sincerely.

**Comment by YIN95** [comment]
the same

**Comment by MrYu001** [comment]
rae you reading in the&nbsp;Royal Institute of Technology? can i ask some infomation from you about it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wenjie"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:53
收件人:&nbsp;"StanfordVL/STR-PIP"<STR-PIP@noreply.github.com&gt;;
抄送:&nbsp;"@于"<1083566157@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [StanfordVL/STR-PIP] Codes (#1)





 
the same

**Comment by eadeli** [comment]
Thank you for your interest. We will put them out soon.

**Comment by Chudbrochil** [comment]
The code is up now. We are still working on making sure everything is runnable outside our Stanford cluster environment.
