### ISSUE TITLE
Regarding code release

### ISSUE THREAD

**Issue by Vaishnvi** [StanfordVL/STR-PIP#2]
Hi @pirobot / @jgwak / @yukezhu / @ranjaykrishna / @ahaque 

It's a splendid and interesting research work. Can you please let know the plan to release code for this?

Thanks and Regards,
Vaishnavi

**Comment by eadeli** [comment]
Thank you for your interest.  We will put them out soon.

**Comment by Chudbrochil** [comment]
The code is up now. We are still working on making sure everything is runnable outside our Stanford cluster environment.
