### ISSUE TITLE
Dataset no response and code is still not there

### ISSUE THREAD

**Issue by MoonBlvd** [StanfordVL/STR-PIP#4]
Hi, thank you for this great work. I have requested for the dataset 1 week ago and have not heard any response yet. And I'm also wondering when do you plan to release your code. Thank you!

**Comment by YIN95** [comment]
无语 看来不会有了

**Comment by MoonBlvd** [comment]
@YIN95 你也拿不到数据集吗

**Comment by YIN95** [comment]
而且发了邮件连回复都不肯回复

**Comment by eadeli** [comment]
We will be releasing the codes soon. Thank you for your interest. 

Please note the dataset is released on the dataset webpage and not here. Please note that to acquire the dataset, you need to work with Stanford and TRI legal teams and sign the user agreement documents first.

**Comment by Chudbrochil** [comment]
The code is up now. We are still working on making sure everything is runnable outside our Stanford cluster environment.
