### ISSUE TITLE
Release date - code 

### ISSUE THREAD

**Issue by segermans** [StanfordVL/STR-PIP#5]
Dear authors,

I sent an e-mail to mr. Adrien Gaidon regarding the release of the code; according to mr. Gaidon, publication of the code got delayed a bit and he advised me to open a GitHub Issue about this. Can you please inform me regarding the actual release date?

 I am really looking forward to work with this code for my research!

Thanks.

Best regards,

Seger

**Comment by eadeli** [comment]
We will be releasing the codes soon. Thank you for your interest.

**Comment by segermans** [comment]
Dear mr. Adeli,

Thanks for the quick reply! Can you give me a rough (!) indication how long it will take for the code to become available? 
I am asking because my interpretation of 'soon' might be different to yours 😉! 
Have a great day.

Cheers, Seger

**Comment by Chudbrochil** [comment]
The code is up now. We are still working on making sure everything is runnable outside our Stanford cluster environment.
